### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by boriskezikov** [boriskezikov/linkedinbot#11]
В базе щас уже около 500 аккаунтов зареганных и хочется добавить возможность искать по фильтрам нужные профили. То бишь не тупо все а например: продакты, разрабы и тд. Плюс иметь возможность отфильтровывать линкед аккаунты людей, которые не в Израиле. 

Здесь полет фантазии - чо угодно для удобства юзеров

**Comment by vbmchik** [comment]
в базу добравим таблицу user_attributes для доп свойств для фильтра?
